openapi: 3.0.0
info:
  version: 4.0.0-SNAPSHOT
  title: Mauro Data Mapper
servers:
  - url: 'http://localhost:3000'
paths:
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string